import os
import requests
from dotenv import load_dotenv

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
GROQ_URL = "https://api.groq.com/openai/v1/chat/completions"
MODEL = "llama-3.3-70b-versatile"


def _headers():
    return {
        "Authorization": "Bearer " + GROQ_API_KEY,
        "Content-Type": "application/json"
    }


def _build_params_description(params):
    if not params:
        return "No parameters."
    lines = []
    for p in params:
        required = "required" if p.get("required", True) else "optional"
        location = p.get("in", "path/query/body")
        lines.append("- `" + p["name"] + "` (" + p.get("type", "string") + ", " + required + ", in: " + location + ")")
    return "\n".join(lines)


SYSTEM_PROMPT = "You are an expert API documentation writer. Generate comprehensive, developer-friendly API documentation from code analysis. Always respond with ONLY markdown. No preamble, no explanation outside the doc."


def generate_doc(method, route, params, return_type,
                 auth_required, raw_code, old_doc=None, framework="unknown"):
    try:
        params_desc = _build_params_description(params)
        old_doc_section = ""
        if old_doc:
            old_doc_section = "## Previous Documentation\n" + old_doc + "\n---"

        auth_text = "Yes" if auth_required else "No"
        rt = return_type or "JSON"
        code_snippet = (raw_code or "")[:1500]
        method_upper = method.upper()
        method_lower = method.lower()

        prompt = (
            "Generate complete API documentation for this endpoint.\n\n"
            "Endpoint: " + method_upper + " " + route + "\n"
            "Framework: " + framework + "\n"
            "Auth Required: " + auth_text + "\n"
            "Return Type: " + rt + "\n"
            "Parameters:\n" + params_desc + "\n\n"
            "Source Code:\n" + code_snippet + "\n\n"
            + old_doc_section + "\n\n"
            "Generate docs with this exact structure:\n\n"
            "# " + method_upper + " " + route + "\n\n"
            "## Overview\n"
            "[2-3 sentences: what this endpoint does and when to use it]\n\n"
            "## Real-World Use Case\n"
            "[1-2 sentences: concrete scenario where a developer calls this]\n\n"
            "## Authentication\n"
            "[How to authenticate, or state it is a public endpoint]\n\n"
            "## Parameters\n\n"
            "### Path Parameters\n"
            "| Parameter | Type | Required | Description |\n"
            "|-----------|------|----------|-------------|\n\n"
            "### Query Parameters\n"
            "| Parameter | Type | Required | Default | Description |\n"
            "|-----------|------|----------|---------|-------------|\n\n"
            "### Request Body\n"
            "[For POST/PUT/PATCH: describe fields. For GET/DELETE: Not applicable]\n\n"
            "## Response\n\n"
            "### Success Response\n"
            "**Status:** 200 OK\n"
            "```json\n"
            "{\n"
            '  "example": "realistic response here"\n'
            "}\n"
            "```\n\n"
            "### Error Responses\n"
            "| Status Code | Meaning | When it occurs |\n"
            "|-------------|---------|----------------|\n"
            "| 400 | Bad Request | Invalid input |\n"
            "| 401 | Unauthorized | Missing or invalid token |\n"
            "| 404 | Not Found | Resource does not exist |\n"
            "| 500 | Server Error | Unexpected failure |\n\n"
            "## Code Examples\n\n"
            "### Python\n"
            "```python\n"
            "import requests\n"
            "response = requests." + method_lower + "('http://localhost:8000" + route + "')\n"
            "print(response.json())\n"
            "```\n\n"
            "### JavaScript\n"
            "```javascript\n"
            "fetch('http://localhost:8000" + route + "', {\n"
            "  method: '" + method_upper + "',\n"
            "  headers: {'Content-Type': 'application/json'}\n"
            "}).then(r => r.json()).then(console.log);\n"
            "```\n\n"
            "## Notes\n"
            "[Edge cases, rate limits, common mistakes]\n\n"
            "---\n"
            "*Auto-generated by Living API Docs*"
        )

        payload = {
            "model": MODEL,
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": prompt}
            ],
            "temperature": 0.3,
            "max_tokens": 2048
        }

        response = requests.post(GROQ_URL, headers=_headers(), json=payload, timeout=60)
        response.raise_for_status()
        data = response.json()
        result = data["choices"][0]["message"]["content"]
        print("[Generator] SUCCESS: " + method_upper + " " + route + " (" + str(len(result)) + " chars)")
        return result.strip()

    except Exception as e:
        print("[Generator] FAILED for " + method + " " + route + ": " + str(e))
        return None
