"""
publisher/markdown_exporter.py
Exports approved API documentation as clean Markdown files.
One file per repo containing all approved endpoint docs.
"""

import os
from datetime import datetime
from storage import db

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "generated_docs")


def _repo_slug(repo_url: str) -> str:
    return repo_url.rstrip("/").replace(".git", "").split("github.com/")[-1].replace("/", "_")


def export_markdown(repo_url: str) -> str:
    """
    Export all approved docs for a repo as a single Markdown file.
    Returns the file path on success, or None on failure.
    """
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Gather all approved docs from version history (latest per endpoint)
    endpoints = db.get_endpoints(repo_url)
    if not endpoints:
        print(f"[Markdown] No endpoints found for {repo_url}")
        return None

    repo_info = db.get_repo(repo_url)
    framework = repo_info.get("framework", "Unknown") if repo_info else "Unknown"
    repo_name = repo_url.rstrip("/").split("/")[-1].replace(".git", "")

    lines = []

    # Header
    lines.append(f"# {repo_name} — API Documentation")
    lines.append(f"\n> Auto-generated by **Living API Docs** on {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"> Framework: **{framework.title()}**")
    lines.append(f"> Source: [{repo_url}]({repo_url})\n")
    lines.append("---\n")

    # Table of Contents
    lines.append("## Table of Contents\n")
    approved_count = 0
    for ep in endpoints:
        latest_doc = db.get_latest_approved_doc(repo_url, ep["method"], ep["route"])
        if latest_doc:
            anchor = f"{ep['method'].lower()}-{ep['route'].replace('/', '').replace('{', '').replace('}', '').replace('_', '-')}"
            lines.append(f"- [{ep['method']} {ep['route']}](#{anchor})")
            approved_count += 1

    if approved_count == 0:
        print(f"[Markdown] No approved docs found for {repo_url}")
        return None

    lines.append("\n---\n")

    # Endpoint Documentation
    for ep in endpoints:
        latest_doc = db.get_latest_approved_doc(repo_url, ep["method"], ep["route"])
        if not latest_doc:
            continue

        lines.append(latest_doc)
        lines.append("\n---\n")

    # Footer
    lines.append(f"\n*Generated by Living API Docs | {datetime.now().strftime('%Y-%m-%d')}*")

    # Write file
    slug = _repo_slug(repo_url)
    output_path = os.path.join(OUTPUT_DIR, f"{slug}_api_docs.md")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"[Markdown] Exported to {output_path}")
    return output_path