"""
publisher/swagger_exporter.py
Generates OpenAPI 3.0 (Swagger) YAML specification from approved endpoint data.
This YAML can be pasted into swagger.io/tools/swagger-ui for interactive docs.
"""

import os
import re
import yaml
from datetime import datetime
from storage import db

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "generated_docs")


def _repo_slug(repo_url: str) -> str:
    return repo_url.rstrip("/").replace(".git", "").split("github.com/")[-1].replace("/", "_")


def _route_to_openapi(route: str) -> str:
    """Convert Express :param style to OpenAPI {param} style."""
    return re.sub(r':(\w+)', r'{\1}', route)


def _build_parameters(params: list, route: str) -> list:
    """Build OpenAPI parameter objects from parsed params."""
    openapi_params = []

    # Path params (extracted from route pattern)
    path_params = re.findall(r'\{(\w+)\}', _route_to_openapi(route))
    for pp in path_params:
        openapi_params.append({
            "name": pp,
            "in": "path",
            "required": True,
            "schema": {"type": "string"}
        })

    # Other params from parser
    for p in params:
        param_in = p.get("in", "query")
        if param_in == "body":
            continue  # handled separately as requestBody

        # Don't duplicate path params
        if p["name"] in path_params:
            continue

        openapi_params.append({
            "name": p["name"],
            "in": param_in if param_in in ("query", "header", "cookie") else "query",
            "required": p.get("required", False),
            "schema": {"type": p.get("type", "string")}
        })

    return openapi_params


def _build_request_body(params: list, method: str) -> dict:
    """Build requestBody for POST/PUT/PATCH endpoints."""
    if method.upper() not in ("POST", "PUT", "PATCH"):
        return None

    body_params = [p for p in params if p.get("in") == "body"]
    if not body_params:
        return {
            "required": True,
            "content": {
                "application/json": {
                    "schema": {"type": "object"}
                }
            }
        }

    properties = {}
    required_fields = []
    for p in body_params:
        properties[p["name"]] = {"type": p.get("type", "string")}
        if p.get("required", True):
            required_fields.append(p["name"])

    schema = {"type": "object", "properties": properties}
    if required_fields:
        schema["required"] = required_fields

    return {
        "required": True,
        "content": {
            "application/json": {
                "schema": schema
            }
        }
    }


def export_swagger(repo_url: str) -> str:
    """
    Generate OpenAPI 3.0 YAML for all approved endpoints in a repo.
    Returns the file path on success, or None on failure.
    """
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    endpoints = db.get_endpoints(repo_url)
    if not endpoints:
        return None

    repo_name = repo_url.rstrip("/").split("/")[-1].replace(".git", "")
    repo_info = db.get_repo(repo_url)
    framework = repo_info.get("framework", "unknown") if repo_info else "unknown"

    # OpenAPI root structure
    openapi_spec = {
        "openapi": "3.0.0",
        "info": {
            "title": f"{repo_name} API",
            "description": f"Auto-generated API documentation for {repo_name}. "
                           f"Framework: {framework.title()}. "
                           f"Generated by Living API Docs on {datetime.now().strftime('%Y-%m-%d')}.",
            "version": "1.0.0",
            "contact": {
                "name": "Living API Docs",
                "url": repo_url
            }
        },
        "servers": [
            {"url": "https://api.yourdomain.com/v1", "description": "Production"},
            {"url": "http://localhost:8000", "description": "Local development"}
        ],
        "paths": {}
    }

    # Build paths
    for ep in endpoints:
        latest_doc = db.get_latest_approved_doc(repo_url, ep["method"], ep["route"])
        if not latest_doc:
            continue

        method = ep["method"].lower()
        openapi_route = _route_to_openapi(ep["route"])

        if openapi_route not in openapi_spec["paths"]:
            openapi_spec["paths"][openapi_route] = {}

        params = ep.get("params") or []

        operation = {
            "summary": f"{ep['method']} {ep['route']}",
            "description": f"Auto-documented endpoint. See markdown docs for full details.",
            "operationId": f"{method}_{ep['route'].replace('/', '_').replace('{', '').replace('}', '').strip('_')}",
            "parameters": _build_parameters(params, ep["route"]),
            "responses": {
                "200": {
                    "description": "Successful response",
                    "content": {
                        "application/json": {
                            "schema": {"type": "object"}
                        }
                    }
                },
                "400": {"description": "Bad request"},
                "401": {"description": "Unauthorized"},
                "404": {"description": "Not found"},
                "500": {"description": "Internal server error"}
            }
        }

        # Add security if auth required
        if ep.get("auth_required"):
            openapi_spec.setdefault("components", {}).setdefault("securitySchemes", {})
            openapi_spec["components"]["securitySchemes"]["BearerAuth"] = {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
            operation["security"] = [{"BearerAuth": []}]

        # Add requestBody for mutating methods
        request_body = _build_request_body(params, ep["method"])
        if request_body:
            operation["requestBody"] = request_body

        openapi_spec["paths"][openapi_route][method] = operation

    if not openapi_spec["paths"]:
        return None

    # Write YAML file
    slug = _repo_slug(repo_url)
    output_path = os.path.join(OUTPUT_DIR, f"{slug}_swagger.yaml")

    with open(output_path, "w", encoding="utf-8") as f:
        yaml.dump(openapi_spec, f, default_flow_style=False, allow_unicode=True, sort_keys=False)

    print(f"[Swagger] Exported to {output_path}")
    return output_path